//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class SetRobotStatusRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/SetRobotStatus";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public bool free;

        public SetRobotStatusRequest()
        {
            this.robot_id = 0;
            this.free = false;
        }

        public SetRobotStatusRequest(int robot_id, bool free)
        {
            this.robot_id = robot_id;
            this.free = free;
        }

        public static SetRobotStatusRequest Deserialize(MessageDeserializer deserializer) => new SetRobotStatusRequest(deserializer);

        private SetRobotStatusRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.free);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.free);
        }

        public override string ToString()
        {
            return "SetRobotStatusRequest: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\nfree: " + free.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
