//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class OpenTaskListMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/OpenTaskList";
        public override string RosMessageName => k_RosMessageName;
        public int taskId; // might not be necessary
        public int packageId;
        public float pos_x;
        public float pos_y;
        public float pos_z;
        public int targetLocation; // inventory slot in counter 0-49

        public OpenTaskListMsg()
        {
            this.taskId = 0;
            this.packageId = 0;
            this.pos_x = 0;
            this.pos_y = 0;
            this.pos_z = 0;
            this.targetLocation = 0;
        }

        public OpenTaskListMsg(int taskId, int packageId, float pos_x, float pos_y, float pos_z, int targetLocation)
        {
            this.taskId = taskId;
            this.packageId = packageId;
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
            this.targetLocation = targetLocation;
        }

        public static OpenTaskListMsg Deserialize(MessageDeserializer deserializer) => new OpenTaskListMsg(deserializer);

        private OpenTaskListMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.taskId);
            deserializer.Read(out this.packageId);
            deserializer.Read(out this.pos_x);
            deserializer.Read(out this.pos_y);
            deserializer.Read(out this.pos_z);
            deserializer.Read(out this.targetLocation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(taskId);
            serializer.Write(packageId);
            serializer.Write(pos_x);
            serializer.Write(pos_y);
            serializer.Write(pos_z);
            serializer.Write(targetLocation);
        }

        public override string ToString()
        {
            return "OpenTaskListMsg: " +
            "\ntaskId: " + taskId.ToString() +
            "\npackageId: " + packageId.ToString() +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString() + 
            "\ntargetLocation: " + targetLocation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
