//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class OpenTasksMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/OpenTasks";
        public override string RosMessageName => k_RosMessageName;

        public int task_id;
        public int package_id;
        public float pos_x;
        public float pos_y;
        public float pos_z;
        public int target_location;

        public OpenTasksMsg()
        {
            this.task_id = 0;
            this.package_id = 0;
            this.pos_x = 0.0f;
            this.pos_y = 0.0f;
            this.pos_z = 0.0f;
            this.target_location = 0;
        }

        public OpenTasksMsg(int task_id, int package_id, float pos_x, float pos_y, float pos_z, int target_location)
        {
            this.task_id = task_id;
            this.package_id = package_id;
            this.pos_x = pos_x;
            this.pos_y = pos_y;
            this.pos_z = pos_z;
            this.target_location = target_location;
        }

        public static OpenTasksMsg Deserialize(MessageDeserializer deserializer) => new OpenTasksMsg(deserializer);

        private OpenTasksMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.package_id);
            deserializer.Read(out this.pos_x);
            deserializer.Read(out this.pos_y);
            deserializer.Read(out this.pos_z);
            deserializer.Read(out this.target_location);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.package_id);
            serializer.Write(this.pos_x);
            serializer.Write(this.pos_y);
            serializer.Write(this.pos_z);
            serializer.Write(this.target_location);
        }

        public override string ToString()
        {
            return "OpenTasksMsg: " +
            "\ntask_id: " + task_id.ToString() +
            "\npackage_id: " + package_id.ToString() +
            "\npos_x: " + pos_x.ToString() +
            "\npos_y: " + pos_y.ToString() +
            "\npos_z: " + pos_z.ToString() +
            "\ntarget_location: " + target_location.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
