//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class PackageSpawnMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/PackageSpawn";
        public override string RosMessageName => k_RosMessageName;

        public int package_id;
        public int spawn_location;
        public int target_location;
        public bool to_storage;

        public PackageSpawnMsg()
        {
            this.package_id = 0;
            this.spawn_location = 0;
            this.target_location = 0;
            this.to_storage = false;
        }

        public PackageSpawnMsg(int package_id, int spawn_location, int target_location, bool to_storage)
        {
            this.package_id = package_id;
            this.spawn_location = spawn_location;
            this.target_location = target_location;
            this.to_storage = to_storage;
        }

        public static PackageSpawnMsg Deserialize(MessageDeserializer deserializer) => new PackageSpawnMsg(deserializer);

        private PackageSpawnMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.package_id);
            deserializer.Read(out this.spawn_location);
            deserializer.Read(out this.target_location);
            deserializer.Read(out this.to_storage);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.package_id);
            serializer.Write(this.spawn_location);
            serializer.Write(this.target_location);
            serializer.Write(this.to_storage);
        }

        public override string ToString()
        {
            return "PackageSpawnMsg: " +
            "\npackage_id: " + package_id.ToString() +
            "\nspawn_location: " + spawn_location.ToString() +
            "\ntarget_location: " + target_location.ToString() +
            "\nto_storage: " + to_storage.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
